# 公開するページのURL
baseURL = "https://zumahun.github.io/azumax"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "FPGA enjoy joy joy!"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "Kohei Azuma"
    bio = "FPGA大好き少年です"
    avatar = "img/avatar1.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#e22d30"

# SNS等のユーザー名
[Params.widgets.social]
  instagram = "azuma1225"
  github = "zumahun"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

